name: Deploy Laravel App to Azure

on:
  push:
    branches:
      - master # or your working branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, bcmath, curl, gd, mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies and build
        run: |
          npm install
          npm run build

      - name: Run Laravel commands
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan migrate --force

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: laravel-story-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
