name: Deploy Laravel App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js dependencies and build
        run: |
          npm install
          npm run build

      - name: Laravel config/migrate
        run: |
          php artisan config:cache
          php artisan migrate --force

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-app-name # change this
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
